on: [push]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Configure Git Safe Directory
      run: git config --global --add safe.directory /github/workspace
    - name: Build and Deploy Nikola
      uses: Junypr/nikola-action@v4
      with:
        dry_run: false
